language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files
services:
  - mysql

php:
  - 7.2

env:

  - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.2 COVERAGE=true

matrix:
  # For each PHP version we exclude the coverage env, except for PHP 7.1
  exclude:
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
  - composer require "orchestra/testbench:${ILLUMINATE_VERSION/5\./3\.}" --no-update --prefer-dist
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist
  - mysql -e 'create database fix;'


install: travis_retry composer install --no-interaction --prefer-dist

before_script:
  - phpenv config-add ~/xdebug.ini
  - cp .env.travis .env


script:
  - php artisan key:generate
  - vendor/bin/phpunit

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then travis_retry php vendor/bin/php-coveralls; fi"

notifications:
  email: false
