name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
       cp .env.example .env
       php -v
       composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
       php artisan key:generate
       
